language: node_js

node_js:
  - '8'
  - '10'
  - '12'

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn --non-interactive --frozen-lockfile

script:
  # - yarn audit
  - yarn lint
  - yarn test
  - yarn coverage
