name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: ['12', '10', '8']
    name: Node ${{ matrix.node }} (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Falcon dependencies
        run: yarn --non-interactive --frozen-lockfile
      - name: Lint project files
        run: yarn lint
      - name: Run Falcon tests
        run: yarn test
      - name: Collect Code Coverage
        run: yarn coverage -t ${{ secrets.CODECOV_TOKEN }}
